apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: shkeeper
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
