apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-docker-entrypoint-initdb-d
  namespace: shkeeper
data:
  create_db.sql: |
    CREATE DATABASE IF NOT EXISTS `shkeeper`;
    CREATE DATABASE IF NOT EXISTS `ethereum-shkeeper`;
    CREATE DATABASE IF NOT EXISTS `bnb-shkeeper`;
