{{ if .Values.btc.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: bitcoin-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
{{ if .Values.ltc.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: litecoin-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
{{ if .Values.doge.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dogecoin-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
{{ if .Values.usdt.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: usdt-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
{{- if or .Values.eth.enabled .Values.eth_usdt.enabled .Values.eth_usdc.enabled}}
---
apiVersion: v1
kind: Secret
metadata:
  name: eth-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
{{- if or .Values.bnb.enabled .Values.bnb_usdt.enabled .Values.bnb_usdc.enabled}}
---
apiVersion: v1
kind: Secret
metadata:
  name: bnb-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
{{- if .Values.xrp.enabled}}
---
apiVersion: v1
kind: Secret
metadata:
  name: xrp-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
