#
# General
#

shkeeper:
  image: vsyshost/shkeeper

dev:
  imagePullSecrets:

storageClassName:

#
# BTC and forks
#

btc:
  enabled: true
ltc:
  enabled: true
doge:
  enabled: true

#
# Tron
#

tron:
  server:
    host: 'tron-shkeeper'
    port: 6000

usdt:
  enabled: false
usdc:
  enabled: false

#
# Ethereum
#

eth_fullnode:
  enabled: false
  url: http://ethereum:8545
  mainnet: true
  nodeSelector: {}
  tolerations: {}

ethereum_shkeeper:
  image: vsyshost/ethereum-shkeeper

eth:
  enabled: false
eth_usdt:
  enabled: false
eth_usdc:
  enabled: false
