#
# General
#

dev:
  imagePullSecrets:

storageClassName:

#
# Shkeeper
#

shkeeper:
  image: vsyshost/shkeeper:1.1.8

#
# BTC and forks
#

btc:
  enabled: true
ltc:
  enabled: true
doge:
  enabled: true

#
# Tron
#

tron_fullnode:
  enabled: false
  url: http://java-tron:8090
  solidity_url: http://java-tron:8091
  mainnet: true
  JAVA_TOOL_OPTIONS: ""
  nodeSelector: {}
  tolerations: []

tron_shkeeper:
  image: vsyshost/tron-shkeeper:1.0.5
  host: 'tron-shkeeper'
  port: 6000

trx:
  enabled: false
usdt:
  enabled: false
usdc:
  enabled: false

#
# Ethereum
#

eth_fullnode:
  enabled: false
  url: http://ethereum:8545
  mainnet: true
  nodeSelector: {}
  tolerations: []

ethereum_shkeeper:
  image: vsyshost/ethereum-shkeeper:1.0.3

eth:
  enabled: false
eth_usdt:
  enabled: false
eth_usdc:
  enabled: false

#
# Monero
#

monero:

  enabled: false
  image: vsyshost/monero:v0.18.1.2
  mainnet: true

  fullnode:
    enabled: false
    monerod:
      host: "monerod"
      port: "1111"
      user: "monerod"
      password: "monerod"
      nodeSelector: {}
      tolerations: []
