apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: shkeeper
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      hostname: rabbitmq
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: shkeeper
          - name: RABBITMQ_DEFAULT_PASS
            value: shkeeper
          - name: RABBITMQ_DEFAULT_VHOST
            value: celery
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq/mnesia
      volumes:
      - name: rabbitmq
        persistentVolumeClaim:
          claimName: rabbitmq
