apiVersion: apps/v1
kind: Deployment
metadata:
  name: shkeeper-deployment
  namespace: shkeeper
  labels:
    app.kubernetes.io/instance: shkeeper-vsys
    app.kubernetes.io/name: shkeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: shkeeper-vsys
      app.kubernetes.io/name: shkeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: shkeeper-vsys
        app.kubernetes.io/name: shkeeper
    spec:

      {{- with .Values.dev.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      hostname: shkeeper
      containers:
      - name: shkeeper
        image: {{ .Values.shkeeper.image }}
        ports:
        - containerPort: 5000
        env:
          - name: TRON_API_SERVER_HOST
            value: {{ .Values.tron_shkeeper.host }}
          - name: TRON_API_SERVER_PORT
            value: {{ .Values.tron_shkeeper.port | quote }}
          - name: BTC_WALLET
            value: {{ if .Values.btc.enabled }}enabled{{ else }}disabled{{ end }}
          - name: LTC_WALLET
            value: {{ if .Values.ltc.enabled }}enabled{{ else }}disabled{{ end }}
          - name: DOGE_WALLET
            value: {{ if .Values.doge.enabled }}enabled{{ else }}disabled{{ end }}
          - name: USDT_WALLET
            value: {{ if .Values.usdt.enabled }}enabled{{ else }}disabled{{ end }}
          - name: USDC_WALLET
            value: {{ if .Values.usdc.enabled }}enabled{{ else }}disabled{{ end }}
          - name: ETH_WALLET
            value: {{ if .Values.eth.enabled }}enabled{{ else }}disabled{{ end }}
          - name: ETH_USDT_WALLET
            value: {{ if .Values.eth_usdt.enabled }}enabled{{ else }}disabled{{ end }}
          - name: ETH_USDC_WALLET
            value: {{ if .Values.eth_usdc.enabled }}enabled{{ else }}disabled{{ end }}
          - name: MONERO_WALLET
            value: {{ if .Values.monero.enabled }}enabled{{ else }}disabled{{ end }}
          {{- if .Values.btc.enabled }}
          - name: BTC_USERNAME
            valueFrom:
              secretKeyRef:
                name: bitcoin-rpc
                key: username
                optional: false
          - name: BTC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bitcoin-rpc
                key: password
                optional: false
          {{- end }}
          {{- if .Values.ltc.enabled }}
          - name: LTC_USERNAME
            valueFrom:
              secretKeyRef:
                name: litecoin-rpc
                key: username
                optional: false
          - name: LTC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: litecoin-rpc
                key: password
                optional: false
          {{- end }}
          {{- if .Values.doge.enabled }}
          - name: DOGE_USERNAME
            valueFrom:
              secretKeyRef:
                name: dogecoin-rpc
                key: username
                optional: false
          - name: DOGE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dogecoin-rpc
                key: password
                optional: false
          {{- end }}
          {{- if .Values.usdt.enabled }}
          - name: USDT_USERNAME
            valueFrom:
              secretKeyRef:
                name: usdt-rpc
                key: username
                optional: false
          - name: USDT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: usdt-rpc
                key: password
                optional: false
          {{- end }}
          {{- if .Values.usdc.enabled }}
          - name: USDC_USERNAME
            valueFrom:
              secretKeyRef:
                name: usdt-rpc
                key: username
                optional: false
          - name: USDC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: usdt-rpc
                key: password
                optional: false
          {{- end }}
          {{- if or .Values.eth.enabled .Values.eth_usdt.enabled .Values.eth_usdc.enabled}}
          - name: ETH_USERNAME
            valueFrom:
              secretKeyRef:
                name: eth-rpc
                key: username
                optional: false
          - name: ETH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eth-rpc
                key: password
                optional: false
          {{- end }}
          {{- if .Values.monero.enabled }}
          - name: MONERO_WALLET_RPC_USER
            valueFrom:
              secretKeyRef:
                name: monero-wallet-rpc
                key: username
                optional: false
          - name: MONERO_WALLET_RPC_PASS
            valueFrom:
              secretKeyRef:
                name: monero-wallet-rpc
                key: password
                optional: false
          - name: MONERO_WALLET_RPC_HOST
            value: {{ .Values.monero.fullnode.monerod.host }}
          - name: MONERO_WALLET_RPC_PORT
            value: {{ .Values.monero.fullnode.monerod.port }}
          - name: MONERO_WALLET_RPC_USER
            value: {{ .Values.monero.fullnode.monerod.user }}
          - name: MONERO_WALLET_RPC_PASS
            value: {{ .Values.monero.fullnode.monerod.password }}
          {{- end }}
          - name: SHKEEPER_BTC_BACKEND_KEY
            valueFrom:
              secretKeyRef:
                name: shkeeper-btc-key
                key: password
                optional: false
        volumeMounts:
        - name: shkeeper-db-storage
          mountPath: /shkeeper.io/instance
      volumes:
      - name: shkeeper-db-storage
        persistentVolumeClaim:
          claimName: shkeeper-db-claim
