apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shkeeper-db-claim
  namespace: shkeeper
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph
