apiVersion: v1
kind: Secret
metadata:
  name: bitcoin-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
---
apiVersion: v1
kind: Secret
metadata:
  name: litecoin-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
---
apiVersion: v1
kind: Secret
metadata:
  name: dogecoin-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
